### ISSUE TITLE
If context user is mentioned user there is no notification

### ISSUE THREAD

**Issue by datapharmer** [DouglasCAyers/salesforce-chatter-bot-feeds#1] opened 2018-05-16 21:08 UTC
If the user in the @mention is the context user for the email service then an alert message is not sent even if the posting user is a different user.

A potential workaround could be to use a custom setting or similar to capture the context user and use a different email service/context user if it matches the @mention user.

Ideally Salesforce would just give us some less insane method of reliably alerting users...

![image](https://user-images.githubusercontent.com/6548767/40144208-d40ef658-592b-11e8-8fa0-8dd4475dc47c.png)

**Comment by douglascayers** [comment] 2018-05-17 06:50
Hi @datapharmer, the lack of email notifications when the person mentioned is the same as the author is by design according to https://help.salesforce.com/articleView?id=000170906&type=1

The difficulty in trying to get around that issue via extra settings or email services is that multiple people could be mentioned in the post. Therefore, to ensure that an email notification for the mention did get sent then you would need sufficient number of alternate author ids such that an author could be chosen that was not being mentioned in the post. =/

If your business requirement relies on an email notification, then you may need to use an Email Alert explicitly.

For now, I'm going to mark this as "wontfix" for now but will keep it open for others that come by so they can be aware of this conversation.

Thanks

**Closed as not planned** 2023-03-18 16:34 UTC
Labels: help wanted, wontfix
